export const EXPERIENCES = [
  {
    id: "migracode",
    company: "Migracode",
    role: "Desenvolvedor Full Stack Jr",
    period: "Abr 2025 - Atualmente",
    description:
      "Atuação no desenvolvimento, manutenção e evolução de uma plataforma de monitoramento industrial em tempo real baseada em microsserviços, com foco em integrações, visualização de dados, performance e confiabilidade.",
    responsibilities: [
      "Desenvolvimento end-to-end de funcionalidades com React, TypeScript, Tailwind CSS, Node.js e AdonisJS",
      "Integração com dados industriais em tempo real via WebSockets e protocolo Modbus",
      "Criação de dashboards analíticos, diagramas de equipamentos e visualizações interativas com React Flow, ECharts e Recharts",
      "Otimização de consultas e modelagem de dados em MySQL e MongoDB para análise de grandes volumes de registros",
      "Desenvolvimento de agente de IA aplicado ao domínio industrial para apoiar diagnóstico técnico e geração de ocorrências",
      "Implementação e melhoria de notificações via Email, WhatsApp e Telegram, além de sustentação de aplicação legada em .NET/ASP.NET",
    ],
    technologies: [
      "React",
      "TypeScript",
      "Node.js",
      "AdonisJS",
      "MySQL",
      "MongoDB",
      "WebSockets",
      "Modbus",
      "React Flow",
      "ECharts",
      "Recharts",
      "Tailwind CSS",
      "Docker",
    ],
  },
  {
    id: "freelancer",
    company: "Freelancer",
    role: "Desenvolvedor Web",
    period: "Set 2024 - Atualmente",
    description:
      "Desenvolvimento de sites e aplicações web sob demanda, atuando desde o planejamento até a entrega final, com foco em performance, SEO e experiência do usuário.",
    responsibilities: [
      "Criação de sites com WordPress, Elementor e Nuvemshop",
      "Desenvolvimento de aplicações modernas com React e Vite",
      "Integração com APIs REST e WebSockets",
      "Configuração de hospedagem, domínios e DNS",
      "Otimização de desempenho, SEO e acessibilidade",
    ],
    technologies: [
      "React",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "WordPress",
      "Elementor",
      "HTML",
      "CSS",
    ],
  },
  {
    id: "cubos-academy",
    company: "Cubos Academy",
    role: "Monitor Full Stack (Temporário)",
    period: "Fev 2024 - Jun 2024",
    description:
      "Atuação como monitor técnico, auxiliando alunos no desenvolvimento de aplicações web e na consolidação de fundamentos de programação.",
    responsibilities: [
      "Suporte a alunos em lógica de programação e desenvolvimento web",
      "Auxílio na criação de APIs REST com Node.js e TypeScript",
      "Correção de atividades e revisão de código",
      "Apoio na compreensão de bancos de dados e boas práticas",
      "Realização de atendimentos técnicos via Discord",
    ],
    technologies: ["JavaScript", "TypeScript", "Node.js", "PostgreSQL", "Git"],
  },
  {
    id: "soujunior",
    company: "SouJunior",
    role: "Desenvolvedor Back-end (Voluntário)",
    period: "Ago 2024 - Jul 2025",
    description:
      "Participação no desenvolvimento de aplicações web em ambiente colaborativo, atuando no back-end de um projeto real.",
    responsibilities: [
      "Desenvolvimento de APIs REST com NestJS",
      "Integração com banco de dados PostgreSQL via TypeORM",
      "Colaboração em equipe multidisciplinar",
      "Participação no ciclo completo de desenvolvimento",
    ],
    technologies: [
      "TypeScript",
      "NestJS",
      "Node.js",
      "PostgreSQL",
      "TypeORM",
      "Docker",
      "Git",
      "Git Flow",
    ],
  },
];
